#!/usr/bin/env python3
"""Generate all runtime configs from config.local.yaml (single source of truth).

    ./configure.py

Reads  config.local.yaml (falls back to config.example.yaml with a warning)
Writes gateway/go2rtc.yaml     — streams + ports for the go2rtc gateway
       webapp/config.json      — NVR topology + bridge port for the web UI
       ai/configs/cameras.yaml — camera list + pipeline settings for the detector
       ai/configs/config_infer_primary_yolo26.txt — legacy detector engine config

Generated files are gitignored; credentials exist only in config.local.yaml.
"""

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent


def load():
    local = ROOT / "config.local.yaml"
    cfg = None
    if local.exists():
        cfg = yaml.safe_load(local.read_text())
    if cfg is not None:
        # NVRs managed from the web UI (Settings → Cameras & NVRs) live in a
        # separate overlay so this file's comments and credentials survive.
        cls = ROOT / "output" / "ai_classes.json"
        if cls.exists():
            try:
                data = json.loads(cls.read_text())
                sel = data.get("selected") if isinstance(data, dict) else data
                if isinstance(sel, list) and sel:
                    cfg.setdefault("ai", {})["class_filter"] = sel
            except ValueError:
                pass
        override = ROOT / "output" / "nvrs_override.json"
        if override.exists():
            try:
                data = json.loads(override.read_text())
                if isinstance(data.get("nvrs"), list) and data["nvrs"]:
                    cfg["nvrs"] = data["nvrs"]
                # single cameras with arbitrary RTSP URLs (forwarded ports,
                # other brands) — first-class alongside NVR channels
                if isinstance(data.get("cameras"), list):
                    cfg["extra_cameras"] = [
                        c for c in data["cameras"]
                        if isinstance(c, dict) and c.get("id") and c.get("url")]
            except ValueError:
                print("WARNING: output/nvrs_override.json is broken — ignored")
        return cfg
    print("WARNING: config.local.yaml not found — using config.example.yaml")
    print("         copy it to config.local.yaml and fill in real values")
    return yaml.safe_load((ROOT / "config.example.yaml").read_text())


def active_channels(nvr):
    skip = set(nvr.get("skip") or [])
    return [ch for ch in range(1, nvr["channels"] + 1) if ch not in skip]


def cam_key(nvr, ch):
    return f"{nvr['id']}_ch{ch:02d}"


def write_go2rtc(cfg):
    gw = cfg["gateway"]
    upstream = gw.get("upstream", "direct")
    fw = gw.get("forwarder") or {}
    if upstream == "forwarder" and not fw.get("host"):
        sys.exit("gateway.upstream is 'forwarder' but gateway.forwarder.host is not set")
    # Ports here are compose-internal; the proxy publishes gateway.web_port.
    lines = [
        "# GENERATED by configure.py — edit config.local.yaml, not this file.",
        "",
        "api:",
        '  listen: ":1984"',
        '  static_dir: "/webapp"',
        "",
        "rtsp:",
        '  listen: ":8554"',
        "",
        "log:",
        f'  level: {gw.get("log_level", "info")}',
        "",
        "streams:",
    ]
    n = 0
    for nvr in cfg["nvrs"]:
        for ch in active_channels(nvr):
            for profile, subtype in (("sub", 1), ("main", 0)):
                name = f"{cam_key(nvr, ch)}_{profile}"
                if upstream == "forwarder":
                    # upstream go2rtc relay serves the same stream names
                    url = f"rtsp://{fw['host']}:{fw.get('port', 8554)}/{name}"
                else:
                    url = (
                        f"rtsp://{nvr['user']}:{nvr['password']}@{nvr['host']}:{nvr['port']}"
                        f"/cam/realmonitor?channel={ch}&subtype={subtype}"
                    )
                lines.append(f"  {name}: {url}")
                n += 1
    for cam in cfg.get("extra_cameras") or []:
        lines.append(f"  {cam['id']}_main: {cam['url']}")
        lines.append(f"  {cam['id']}_sub: {cam.get('url_sub') or cam['url']}")
        n += 1
    (ROOT / "gateway" / "go2rtc.yaml").write_text("\n".join(lines) + "\n")
    return n


INFER_TEMPLATE = """\
# GENERATED by configure.py — edit config.local.yaml (ai.model), not this file.
# YOLO26 is end-to-end (NMS-free): cluster-mode=4 + trivial custom parser.

[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
model-engine-file=../models/{model}_fp16_gpu{gpu}.engine
onnx-file=../models/{model}.onnx
labelfile-path=labels.txt
infer-dims=3;640;640
batch-size={batch}
network-mode=2
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=4
maintain-aspect-ratio=1
symmetric-padding=1
parse-bbox-func-name=NvDsInferParseYolo26
custom-lib-path=../src/nvdsinfer_yolo26/libnvdsinfer_yolo26.so

[class-attrs-all]
pre-cluster-threshold=0.1
topk=300
"""


POSE_TEMPLATE = """\
# GENERATED by configure.py — edit config.local.yaml (ai.pose), not this file.
# YOLO26-Pose, end-to-end output [300 x 57] = box(4)+conf+cls+17*(x,y,conf).
# network-type=100 + output-tensor-meta: raw tensor decoded in Python
# (ai/src/parse_pose.py); keypoints ride on the SAME person records.

[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
model-engine-file=../models/{model}_fp16_gpu{gpu}.engine
onnx-file=../models/{model}.onnx
infer-dims=3;640;640
batch-size={batch}
network-mode=2
interval={interval}
gie-unique-id=2
process-mode=1
network-type=100
output-tensor-meta=1
maintain-aspect-ratio=1
symmetric-padding=1
"""


DEPTH_TEMPLATE = """\
# GENERATED by configure.py — edit config.local.yaml (ai.depth), not this file.
# Depth Anything V2-Small (Apache-2.0), ImageNet norm folded into the ONNX
# (net-scale-factor=1, raw 0-255 RGB in). Full-frame stretch (no letterbox)
# so the depth map覆盖 the whole scene like the display layer does.
# interval=N -> inference every (N+1)th frame; publish capped at 3 fps.

[property]
gpu-id=0
net-scale-factor=1.0
model-color-format=0
model-engine-file=../models/{model}_fp16_gpu{gpu}.engine
onnx-file=../models/{model}.onnx
infer-dims=3;196;252
batch-size={batch}
network-mode=2
interval={interval}
gie-unique-id=3
process-mode=1
network-type=100
output-tensor-meta=1
maintain-aspect-ratio=0
"""


def write_infer(cfg, n_cameras):
    gpu = int(cfg.get("ai", {}).get("gpu_id", 0))
    model = cfg.get("ai", {}).get("model", "yolo26s")
    engine = ROOT / "ai" / "models" / f"{model}_fp16_gpu{gpu}.engine"
    if not engine.exists():
        print(f"WARNING: {engine.name} not built yet — run: scripts/setup_model.sh {model}")
    (ROOT / "ai" / "configs" / "config_infer_primary_yolo26.txt").write_text(
        INFER_TEMPLATE.format(model=model, batch=min(n_cameras, 32), gpu=gpu)
    )
    pose = cfg.get("ai", {}).get("pose", {})
    if pose.get("enabled"):
        pmodel = pose.get("model", "yolo26l-pose")
        pengine = ROOT / "ai" / "models" / f"{pmodel}_fp16_gpu{gpu}.engine"
        if not pengine.exists():
            print(f"WARNING: {pengine.name} not built yet — export the "
                  f"ONNX and run trtexec (see ai/scripts/build_trt_engine.sh)")
        (ROOT / "ai" / "configs" / "config_infer_pose_yolo26.txt").write_text(
            POSE_TEMPLATE.format(model=pmodel, batch=min(n_cameras, 32),
                                 interval=int(pose.get("interval", 0)),
                                 gpu=gpu)
        )
        print(f"ai pose config           model={pmodel}")
    depth = cfg.get("ai", {}).get("depth", {})
    if depth.get("enabled"):
        dmodel = depth.get("model", "dav2s-depth")
        dengine = ROOT / "ai" / "models" / f"{dmodel}_fp16_gpu{gpu}.engine"
        if not dengine.exists():
            print(f"WARNING: {dengine.name} not built yet")
        (ROOT / "ai" / "configs" / "config_infer_depth_dav2.txt").write_text(
            DEPTH_TEMPLATE.format(model=dmodel, batch=min(n_cameras, 32),
                                  interval=int(depth.get("interval", 1)),
                                  gpu=gpu)
        )
        print(f"ai depth config          model={dmodel}")
    return model


def write_webapp(cfg):
    out = {
        "classes": cfg.get("ai", {}).get("class_filter") or [],
        "model": cfg.get("ai", {}).get("model", "yolo26s"),
        "aspect": cfg.get("ui", {}).get("aspect", "16:9"),
        "nvrs": [
            {
                "id": nvr["id"],
                "name": nvr["name"],
                "host": nvr["host"],
                "channels": nvr["channels"],
                "skip": nvr.get("skip") or [],
            }
            for nvr in cfg["nvrs"]
        ],
    }
    out["extra_cameras"] = [
        {"id": c["id"], "name": c.get("name") or c["id"]}
        for c in cfg.get("extra_cameras") or []]
    (ROOT / "webapp" / "config.json").write_text(json.dumps(out, indent=2) + "\n")


def write_ai(cfg):
    ai = cfg["ai"]
    gw = cfg["gateway"]
    wanted = ai.get("cameras", "all")

    cameras = []
    for nvr in cfg["nvrs"]:
        for ch in active_channels(nvr):
            key = cam_key(nvr, ch)
            if wanted == "all" or key in wanted:
                # compose-internal DNS name of the gateway service
                cameras.append(
                    {"id": key, "uri": f"rtsp://gateway:8554/{key}_main"}
                )
    for cam in cfg.get("extra_cameras") or []:
        if wanted == "all" or cam["id"] in wanted:
            cameras.append({"id": cam["id"],
                            "uri": f"rtsp://gateway:8554/{cam['id']}_main"})
    if not cameras:
        sys.exit("ai.cameras matched no channels — check config.local.yaml")

    out = {
        "gpu_id": ai.get("gpu_id", 0),
        "streammux": ai.get("streammux", {}),
        "inference": {
            "config": "configs/config_infer_primary_yolo26.txt",
            "interval": ai.get("infer_interval", 0),
        },
        "pose": {
            "enabled": bool(ai.get("pose", {}).get("enabled")),
            "config": "configs/config_infer_pose_yolo26.txt",
            "min_confidence": float(
                ai.get("pose", {}).get("min_confidence", 0.35)),
        },
        "depth": {
            "enabled": bool(ai.get("depth", {}).get("enabled")),
            "config": "configs/config_infer_depth_dav2.txt",
            "publish_dir": "output/calib/track23/live",
            "publish_fps": float(
                ai.get("depth", {}).get("publish_fps", 2.0)),
        },
        "tracker": {
            **ai.get("tracker", {"enabled": True}),
            "config": "configs/config_tracker_NvDCF.yml",
        },
        "output": {
            "jsonl": {"enabled": False, "path": "output/detections.jsonl"},
            "http": {
                "enabled": True,
                "url": "http://bridge:8081/ingest",
                "batch_size": 50,
                "flush_interval_s": 0.3,
                "timeout_s": 5,
            },
        },
        # Detector floor: matches pre-cluster-threshold. The user-facing
        # threshold is applied live by the bridge (web UI -> AI settings).
        "min_confidence": 0.10,
        "class_filter": ai.get("class_filter", []),
        "cameras": cameras,
    }
    text = (
        "# GENERATED by configure.py — edit config.local.yaml, not this file.\n"
        + yaml.safe_dump(out, sort_keys=False)
    )
    (ROOT / "ai" / "configs" / "cameras.yaml").write_text(text)
    return len(cameras)


def main():
    cfg = load()
    n_streams = write_go2rtc(cfg)
    write_webapp(cfg)
    n_cams = write_ai(cfg)
    model = write_infer(cfg, n_cams)
    print(f"gateway/go2rtc.yaml      {n_streams} streams")
    print(f"webapp/config.json       ok")
    print(f"ai/configs/cameras.yaml  {n_cams} cameras")
    print(f"ai infer config          model={model}")
    print("apply with: docker compose up -d")


if __name__ == "__main__":
    main()
